name: Lint

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  # These permissions are required by golangci-lint to create annotations for PRs.
  # https://github.com/golangci/golangci-lint-action?tab=readme-ov-file
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint-go:
    name: Lint Go (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod
      - name: Run go version
        run: go version
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
      # - name: Run govulncheck
        # uses: golang/govulncheck-action@v1
